greenTea:
   productCode: "GR1"
   name: "Green Tea"
   price: 3.11
strawberries:
   productCode: "SR1"
   name: "Strawberries"
   price: 5.00   
coffee:
   productCode: "CF1"
   name: "Coffee"
   price: 11.23 




